<a href="https://colab.research.google.com/github/akk-026/breast-cancer-classification/blob/main/Breast_Cancer_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing our cancer dataset

dataset = pd.read_csv('cancer.csv')

#defining features and target

X = dataset.iloc[:,1:31].values
Y = dataset.iloc[:, 31].values

In [ ]:
#examining dataset

dataset.head()

id  radius_mean  ...  fractal_dimension_worst  diagnosis
0    842302        17.99  ...                  0.11890          M
1    842517        20.57  ...                  0.08902          M
2  84300903        19.69  ...                  0.08758          M
3  84348301        11.42  ...                  0.17300          M
4  84358402        20.29  ...                  0.07678          M

[5 rows x 32 columns]

In [ ]:
#finding dimensions of dataset

print ("Cancer dataset dimensions: {}".format(dataset.shape))

Cancer dataset dimensions: (569, 32)


In [ ]:
#finding any null or missing points within dataset

dataset.isnull().sum()

id                         0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
diagnosis                  0
dtype: int64

In [ ]:
#encoding categorical data values

from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
print (Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

In [ ]:
#splitting dataset into 75% Training set and 25% Test set

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split (X, Y, test_size = 0.25, random_state = 0)

In [ ]:
#Feature scaling , standardizing features

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#importing for stats

from sklearn.metrics import accuracy_score

In [ ]:
#Using KNN

from sklearn.neighbors import KNeighborsClassifier
classifier_1 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_1.fit(X_train, Y_train)
Y_pred1 = classifier_1.predict(X_test)
print (accuracy_score(Y_test, Y_pred1))

0.951048951048951


In [ ]:
#confusion matrix for KNN

from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(Y_test, Y_pred1)
print(cm1)

[[89  1]
 [ 6 47]]


In [ ]:
#Using SVM with linear kernel

from sklearn.svm import SVC
classifier_2 = SVC(kernel = 'linear', random_state = 0)
classifier_2.fit(X_train, Y_train)
Y_pred2 = classifier_2.predict(X_test)
print (accuracy_score(Y_test, Y_pred2))

0.972027972027972


In [ ]:
#confusion matrix for SVM with linear kernel

cm2 = confusion_matrix(Y_test, Y_pred2)
print(cm2)

[[88  2]
 [ 2 51]]


In [ ]:
#Using SVM with rbf kernel

classifier_3 = SVC(kernel = 'rbf', random_state = 0)
classifier_3.fit(X_train, Y_train)
Y_pred3 = classifier_3.predict(X_test)
print(accuracy_score(Y_test, Y_pred3))

0.965034965034965


In [ ]:
#confusion matrix for SVM with rbf kernel

cm3 = confusion_matrix(Y_test, Y_pred3)
print(cm3)

[[88  2]
 [ 3 50]]


In [ ]:
#Using Decision Trees

from sklearn.tree import DecisionTreeClassifier
classifier_4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_4.fit(X_train, Y_train)
Y_pred4 = classifier_4.predict(X_test)
print(accuracy_score(Y_test, Y_pred4))

0.958041958041958


In [ ]:
#confusion matrix for Decision Trees

cm4 = confusion_matrix(Y_test, Y_pred4)
print(cm4)

[[86  4]
 [ 2 51]]


In [ ]:
#Using Naive Bayes

from sklearn.naive_bayes import GaussianNB
classifier_5 = GaussianNB()
classifier_5.fit(X_train, Y_train)
Y_pred5 = classifier_5.predict(X_test)
print(accuracy_score(Y_test, Y_pred5))

0.916083916083916


In [ ]:
#confusion matrix for Naive Bayes

cm5 = confusion_matrix(Y_test, Y_pred5)
print(cm5)

[[84  6]
 [ 6 47]]
